Add more verbs
dariusk/corpora pull request #420
Opened 2023-05-02 00:58 UTC by norwd

I'm using this list of verbs to validate PR titles, I've found that some verbs are missing (particularly development related terms like "update", "merge",  "encode" etc...)

I hope these additions are helpful to someone out there 🙂

2023-05-02 03:11 UTC, hugovk requested changes
To fix / become fixed:

2023-05-02 03:11 UTC, hugovk commented on data/words/verbs.json
> +            "past": "breaked"
```suggestion
            "past": "broke"
```

2023-05-02 03:11 UTC, hugovk commented on data/words/verbs.json
> +            "past": "endabled"
```suggestion
            "past": "enabled"
```

2023-05-02 03:11 UTC, hugovk commented on data/words/verbs.json
> +            "past": "restore"
```suggestion
            "past": "restored"
```

2023-05-02 03:38 UTC, norwd commented
> To fix / become fixed:

Fixed now, sorry my spelling is awful 😅

2023-05-02 05:29 UTC, hugovk approved these changes
Thanks! I wonder why the CI is taking so long. Let's give it a bit more time.

2023-05-02 12:12 UTC, hugovk commented
Please could you merge or rebase on `master`?

The old `ubuntu-18.04` CI runner is longer available, https://github.com/dariusk/corpora/pull/421 fixes it.

2023-05-02 12:23 UTC, merged

2023-05-02 12:23 UTC, hugovk commented
Merge / merged, thanks!

2023-05-02 21:34 UTC, norwd commented
> Please could you merge or rebase on `master`?

Ah sorry it was night time for me, looks like it worked out eventually. Thanks! 😄

2023-05-03 03:42 UTC, hugovk commented
You did exactly what I asked for, so thank you!